# Generated by Django 4.1.7 on 2023-03-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed task', max_length=100)),
                ('details', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
