# Generated by Django 4.1.7 on 2023-03-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_task_completed_alter_task_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('hire_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('on_leave', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('building_name', models.CharField(blank=True, max_length=30)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.location'),
        ),
    ]
