# Generated by Django 4.1.7 on 2023-03-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_employee_location_task_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Event',
        ),
    ]
