# Generated by Django 4.1.7 on 2023-03-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_rename_task_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='completed',
            new_name='attended',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='deadline',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='priority',
            new_name='importance',
        ),
    ]
