# Generated by Django 4.1.7 on 2023-03-12 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_rename_completed_event_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 17, 16, 6, 973477)),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
