# Generated by Django 4.1.7 on 2023-03-12 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_event_date_alter_event_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attended',
            new_name='business_trip',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 17, 23, 3, 33154)),
        ),
    ]
