# Generated by Django 4.1.7 on 2023-03-20 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePrivateInfo',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rest_api.employee')),
                ('cnp', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 20, 18, 13, 31, 537342)),
        ),
        migrations.CreateModel(
            name='EmployeeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_summary', models.TextField(blank=True, default="no summary given/ the event hasn't happened yet")),
                ('event_outcome', models.CharField(blank=True, choices=[(1, 'very positive'), (2, 'positive'), (3, 'neutral'), (4, 'negative'), (5, 'very negative')], default='neutral', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.event')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='events',
            field=models.ManyToManyField(through='rest_api.EmployeeEvent', to='rest_api.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='employees',
            field=models.ManyToManyField(through='rest_api.EmployeeEvent', to='rest_api.employee'),
        ),
    ]
