# Generated by Django 4.1.7 on 2023-03-21 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_alter_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeEvent',
            new_name='EventAssignment',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 21, 13, 22, 19, 64003)),
        ),
    ]
